// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class API_EC_TRANSTI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime INVOICEDATE { get; set; }

    public string INVOICENUMBER { get; set; }

    public string ITEM_NO { get; set; }

    public string DESCRIPTION { get; set; }

    public decimal? QUANTITY { get; set; }

    public decimal? UNITPRICE { get; set; }

    public decimal? UNITPRICE_NET { get; set; }

    public decimal? AMOUNT { get; set; }

    public decimal? AMOUNT_NET { get; set; }

    public string CRT_NO { get; set; }

    public DateOnly? CRT_DATE { get; set; }
}