// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class API_EC_TRANS01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string INVOICENUMBER { get; set; }

    public DateTime INVOICEDATE { get; set; }

    public string INVOICETIME { get; set; }

    public string SEL_IDENTIFIER { get; set; }

    public string BUY_IDENTIFIER { get; set; }

    public string BUY_NAME { get; set; }

    public decimal? TOT_AMT { get; set; }

    public decimal? FREE_AMT { get; set; }

    public decimal? ZERO_AMT { get; set; }

    public decimal? TAXED_AMT { get; set; }

    public decimal? TAX_AMT { get; set; }

    public string PRINTMARK { get; set; }

    public string CARRY_TYPE { get; set; }

    public string CARRY_ID { get; set; }

    public string CARRY_ID2 { get; set; }

    public string RANDOM_CODE { get; set; }

    public string NPOBAN { get; set; }

    public string INVFLAG { get; set; }

    public string ORDER_NO { get; set; }

    public string MEM_NAME { get; set; }

    public string MEM_ZCODE { get; set; }

    public string MEM_ADDR { get; set; }

    public string MEM_TEL { get; set; }

    public string MEM_MOBILE { get; set; }

    public string MEM_EMAIL { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? STRANS_DATE { get; set; }
}