// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class DEMOTI
{
    public int id { get; set; }

    public int did { get; set; }

    /// <summary>
    /// 內容
    /// </summary>
    public string content { get; set; }
}