// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_ALLOW01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string AllowanceNumber { get; set; }

    public DateTime? AllowanceDate { get; set; }

    public string sel_Identifier { get; set; }

    public string buy_Identifier { get; set; }

    public string buy_Name { get; set; }

    public string buy_Address { get; set; }

    public string buy_PersonInCharge { get; set; }

    public string buy_TelephoneNumber { get; set; }

    public string buy_FacsimileNumber { get; set; }

    public string buy_EmailAddress { get; set; }

    public string CustomerNumber { get; set; }

    public string RoleRemark { get; set; }

    public string AllowanceType { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public string TRAN_CODE { get; set; }

    public DateTime? CancelDate { get; set; }

    public string CancelTime { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? PTRANS_DATE { get; set; }

    public string PFILE_NA { get; set; }

    public DateTime? STRANS_DATE { get; set; }

    public string SFILE_NA { get; set; }

    public string STRANS_Ret { get; set; }

    public string STRANS_Err { get; set; }

    public string IS_CHK_OK { get; set; }

    public DateTime? CHK_DATE { get; set; }

    public string Turnkey_STATUS { get; set; }

    public string Turnkey_MSG_DTS { get; set; }

    public string Turnkey_SEQNO { get; set; }

    public string Turnkey_SUBSEQNO { get; set; }

    public string IS_B2B { get; set; }

    public DateTime? B2B_EINV_DATEB { get; set; }
}