// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_INPUTINVTI
{
    /// <summary>
    /// 公司別
    /// </summary>
    public string COMP_NO { get; set; }

    /// <summary>
    /// 店別
    /// </summary>
    public string STR_NO { get; set; }

    /// <summary>
    /// 發票號碼
    /// </summary>
    public string InvoiceNumber { get; set; }

    /// <summary>
    /// 發票日期
    /// </summary>
    public DateTime InvoiceDate { get; set; }

    /// <summary>
    /// 明細排列序號
    /// </summary>
    public string SequenceNumber { get; set; }

    /// <summary>
    /// 品名
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 數量
    /// </summary>
    public decimal? Quantity { get; set; }

    /// <summary>
    /// 單位
    /// </summary>
    public string Unit { get; set; }

    /// <summary>
    /// 單價
    /// </summary>
    public decimal? UnitPrice { get; set; }

    /// <summary>
    /// 金額
    /// </summary>
    public decimal? Amount { get; set; }

    /// <summary>
    /// 項次
    /// </summary>
    public string Item { get; set; }

    /// <summary>
    /// 單一欄位備註
    /// </summary>
    public string Remark { get; set; }

    /// <summary>
    /// 相關號碼
    /// </summary>
    public string RelateNumber { get; set; }

    /// <summary>
    /// 課稅別
    /// </summary>
    public string TaxType { get; set; }

    /// <summary>
    /// 建檔者代碼
    /// </summary>
    public string CRT_NO { get; set; }

    /// <summary>
    /// 建檔日期
    /// </summary>
    public DateTime? CRT_DATE { get; set; }
}