// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_TRANSTI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string InvoiceNumber { get; set; }

    public DateTime InvoiceDate { get; set; }

    public string SequenceNumber { get; set; }

    public string Description { get; set; }

    public decimal? Quantity { get; set; }

    public string Unit { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? UnitPrice_Net { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Amount_Net { get; set; }

    public string Item { get; set; }

    public string Remark { get; set; }

    public string RelateNumber { get; set; }

    public string TaxType { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}