// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_TRANS01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string InvoiceNumber { get; set; }

    public DateTime InvoiceDate { get; set; }

    public string InvoiceTime { get; set; }

    public string sel_Identifier { get; set; }

    public string buy_Identifier { get; set; }

    public string buy_Name { get; set; }

    public string buy_Address { get; set; }

    public string buy_PersonInCharge { get; set; }

    public string buy_TelephoneNumber { get; set; }

    public string buy_FacsimileNumber { get; set; }

    public string buy_EmailAddress { get; set; }

    public string CustomerNumber { get; set; }

    public string RoleRemark { get; set; }

    public string CheckNumber { get; set; }

    public string BuyerRemark { get; set; }

    public string MainRemark { get; set; }

    public string CustomsClearanceMark { get; set; }

    public string Category { get; set; }

    public string RelateNumber { get; set; }

    public string InvoiceType { get; set; }

    public string GroupMark { get; set; }

    public string DonateMark { get; set; }

    public string CarrierType { get; set; }

    public string CarrierId1 { get; set; }

    public string CarrierId2 { get; set; }

    public string PrNumberMark { get; set; }

    public string PrNumberMark2 { get; set; }

    public DateTime? PrNumberlDate { get; set; }

    public string NPOBAN { get; set; }

    public string RandomId { get; set; }

    public string RandomNumber { get; set; }

    public decimal? SLIP_PRNumber { get; set; }

    public string Src_Type { get; set; }

    public DateTime? VOID_Date { get; set; }

    public decimal? SalesAmount { get; set; }

    public decimal? FreeTaxSalesAmount { get; set; }

    public decimal? ZeroTaxSalesAmount { get; set; }

    public string TaxType { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? OriginalCurrencyAmount { get; set; }

    public decimal? ExchangeRate { get; set; }

    public string Currency { get; set; }

    public string TRAN_CODE { get; set; }

    public DateTime? CancelDate { get; set; }

    public string CancelTime { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? PTRANS_DATE { get; set; }

    public string PFILE_NA { get; set; }

    public DateTime? STRANS_DATE { get; set; }

    public string SFILE_NA { get; set; }

    public string STRANS_Ret { get; set; }

    public string STRANS_Err { get; set; }

    public string SendNotice { get; set; }

    public DateTime? SENDNOTICE_DATE { get; set; }

    public DateTime? VOIDDATE { get; set; }

    public string VOIDTIME { get; set; }

    public string IS_CHK_OK { get; set; }

    public DateTime? CHK_DATE { get; set; }

    public string Turnkey_STATUS { get; set; }

    public string Turnkey_MSG_DTS { get; set; }

    public string Turnkey_SEQNO { get; set; }

    public string Turnkey_SUBSEQNO { get; set; }

    public string IS_B2B { get; set; }

    public DateTime? B2B_EINV_DATEB { get; set; }

    public string PRIZE_YN { get; set; }

    public string MEM_VIPNO { get; set; }
}