// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_ALLOWTI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string AllowanceNumber { get; set; }

    public string sel_Identifier { get; set; }

    public string buy_Identifier { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string InvoiceNumber { get; set; }

    public string Org_SequenceNumber { get; set; }

    public string Org_Item { get; set; }

    public string Org_Description { get; set; }

    public decimal? Quantity { get; set; }

    public string Unit { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? UnitPrice_Net { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Amount_Net { get; set; }

    public decimal? Tax { get; set; }

    public string All_SequenceNumber { get; set; }

    public string TaxType { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}