// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class Einv_INVNO_CHECK
{
    public string SEL_IDENTIFIER { get; set; }

    public string INVOICETYPE { get; set; }

    public string INV_PERIOD { get; set; }

    public DateTime INV_BDATE { get; set; }

    public DateTime? INV_EDATE { get; set; }

    public string INV_HEAD_NO { get; set; }

    public string INV_BNO { get; set; }

    public string INV_ENO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}