// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_VIPMI
{
    public string CustomerNumber { get; set; }

    public string CarrierId1 { get; set; }

    public string CustomerName { get; set; }

    public string InvoiceMark { get; set; }

    public string DonateMark { get; set; }

    public string PrintMark { get; set; }

    public string PrizeMark { get; set; }

    public string PrizeComm { get; set; }

    public string CustomerEmail { get; set; }

    public string CustomerTelephoneNo { get; set; }

    public string CustomerMobleNo { get; set; }

    public string CustomerZipcode { get; set; }

    public string CustomerAddress { get; set; }

    public string SigninMark { get; set; }

    public string Upd_NO { get; set; }

    public DateTime? Upd_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string NPOBAN { get; set; }
}