// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_PRIZE
{
    public string SEL_IDENTIFIER { get; set; }

    public string INV_PERIOD { get; set; }

    public DateTime INVOICEDATE { get; set; }

    public string INVOICENUMBER { get; set; }

    public string INVOICETIME { get; set; }

    public string SEL_NAME { get; set; }

    public decimal? SALESAMOUNT { get; set; }

    public decimal? PRIZEAMT { get; set; }

    public string RANDOMNUMBER { get; set; }

    public string CARRIERTYPE { get; set; }

    public string CARRIERNAME { get; set; }

    public string CARRIERIDCLEAR { get; set; }

    public string CARRIERIDHIDE { get; set; }

    public string PRIZETYPE { get; set; }

    public string DATATYPE { get; set; }

    public string PRINTMARK { get; set; }

    public DateTime? PRINTDATE { get; set; }

    public DateTime? RecAwardBDATE { get; set; }

    public DateTime? RecAwardEDATE { get; set; }

    public string MEM_NAME { get; set; }

    public string MEM_MOBILE { get; set; }

    public string MEM_EMAIL { get; set; }

    public decimal? TRANS_CNT { get; set; }

    public DateTime? TRANS_TIME { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string MEM_VIPNO { get; set; }
}