// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_SALES_TAX_DECLARE
{
    public string COMP_NO { get; set; }

    public string FORMAT_CODE { get; set; }

    public string TAX_IDENTIFIER { get; set; }

    public decimal? SEQ_NO { get; set; }

    public string DECLARE_YR { get; set; }

    public string DECLARE_MTH { get; set; }

    public string SEL_IDENTIFIER { get; set; }

    public string BUY_IDENTIFIER { get; set; }

    public string INV_HEAD_NO { get; set; }

    public string INV_SERIAL_NO { get; set; }

    public decimal? TOTALAMOUNT { get; set; }

    public string TAXTYPE { get; set; }

    public decimal? TAXAMOUNT { get; set; }

    public string DISCOUNT_CODE { get; set; }

    public string SPACE { get; set; }

    public string SPECIAL_TAX { get; set; }

    public string GROUPMARK { get; set; }

    public string CUSTOMSCLEARANCEMARK { get; set; }

    public DateTime? INVOICEDATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? INV_BDATE { get; set; }

    public DateTime? INV_EDATE { get; set; }
}