// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class EINV_INPUTINV01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string INVOICENUMBER { get; set; }

    public DateTime INVOICEDATE { get; set; }

    public string INVOICETIME { get; set; }

    public string CurrentStatus { get; set; }

    public string sel_Identifier { get; set; }

    public string Sel_Name { get; set; }

    public string buy_Identifier { get; set; }

    public string buy_Name { get; set; }

    public string BuyerRemark { get; set; }

    public string MainRemark { get; set; }

    public string CustomsClearanceMark { get; set; }

    public string Category { get; set; }

    public string RelateNumber { get; set; }

    public string InvoiceType { get; set; }

    public string GroupMark { get; set; }

    public string DonateMark { get; set; }

    public string CarrierType { get; set; }

    public string CarrierId1 { get; set; }

    public string CarrierId2 { get; set; }

    public string PrintMark { get; set; }

    public string NPOBAN { get; set; }

    public string RandomNumber { get; set; }

    public decimal? SalesAmount { get; set; }

    public decimal? FreeTaxSalesAmount { get; set; }

    public decimal? ZeroTaxSalesAmount { get; set; }

    public string TaxType { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal? OriginalCurrencyAmount { get; set; }

    public decimal? ExchangeRate { get; set; }

    public string Currency { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? CancelDate { get; set; }

    public string CancelTime { get; set; }

    public string CancelReason { get; set; }

    public DateTime? RejectDate { get; set; }

    public string RejectTime { get; set; }

    public string RejectReason { get; set; }

    public DateTime? PTRANS_DATE { get; set; }

    public DateTime? STRANS_DATE { get; set; }

    public string SFILE_NA { get; set; }

    public string STRANS_Ret { get; set; }

    public string STRANS_Err { get; set; }
}