// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class FAMERORDER
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateOnly KDATE { get; set; }

    public string ORDER_NO { get; set; }

    public decimal ITEM_NO { get; set; }

    public string ORDER_TYPE { get; set; }

    public string TAX_TYPE { get; set; }

    public string NATURAL_CERT { get; set; }

    public string MOBILE_CERT { get; set; }

    public string NPOBAN { get; set; }

    public string BUY_IDENTIFIER { get; set; }

    public string BUY_CODE { get; set; }

    public string CUST_ID { get; set; }

    public string BUY_NAME { get; set; }

    public string BUY_MOBILE { get; set; }

    public string BUY_TEL { get; set; }

    public string BUY_EMAIL { get; set; }

    public decimal? STAX_AMT { get; set; }

    public decimal? ZEROTAX_AMT { get; set; }

    public decimal? NOTAX_AMT { get; set; }

    public decimal? TAX { get; set; }

    public decimal? TOT_AMT { get; set; }

    public string MEMO { get; set; }

    public string PRODUCT_ID { get; set; }

    public string PRODUCT_DESC { get; set; }

    public decimal? SPRICE { get; set; }

    public decimal? QTY { get; set; }

    public string SUNT_NA { get; set; }

    public string PRODUCT_TAX_TYPE { get; set; }

    public string PRODUCT_MEMO { get; set; }

    public string PRINT_MEMO { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public DateTime? TRANS_DATE { get; set; }

    public DateTime? TRANS_CDATE { get; set; }
}