// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class fnaitem
{
    public string aitem_id { get; set; }

    public string aitem_group { get; set; }

    public string aitem_level { get; set; }

    public string aitem_seq { get; set; }

    public string aitem_name { get; set; }
}