// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class fnxacontmi
{
    public string comp_no { get; set; }

    public int acontmi_no { get; set; }

    public string acontmi_name { get; set; }

    public string acontmi_year { get; set; }

    public string acontmi_month { get; set; }

    public string acontmi_depart { get; set; }

    public string acontmi_stage { get; set; }

    public string acontmi_user { get; set; }

    public string mod_user { get; set; }

    public string mod_dte { get; set; }

    public string crt_user { get; set; }

    public string crt_dte { get; set; }
}