// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class fnxacontti
{
    public string comp_no { get; set; }

    public int acontmi_no { get; set; }

    public string acontti_no { get; set; }

    public string acontti_title { get; set; }

    public int acontti_level { get; set; }

    public int acontti_page_start { get; set; }

    public int acontti_page_end { get; set; }

    public int acontti_jump_page { get; set; }

    public string acontti_group { get; set; }

    public string acontti_print { get; set; }

    public string acontti_flag { get; set; }

    public string acontti_prgarea { get; set; }

    public string acontti_prgno { get; set; }

    public string acontti_param_str { get; set; }

    public string mod_user { get; set; }

    public string mod_dte { get; set; }

    public string crt_user { get; set; }

    public string crt_dte { get; set; }
}