// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class INPZIP5
{
    public string ZIP5 { get; set; }

    public string CITY { get; set; }

    public string AREA { get; set; }

    public string ROAD { get; set; }

    public string SCOPE { get; set; }
}