// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class LINE_LIST
{
    /// <summary>
    /// 流水編號
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 公司別
    /// </summary>
    public string COMPNO { get; set; }

    /// <summary>
    /// 店別
    /// </summary>
    public string STR_NO { get; set; }

    /// <summary>
    /// 抽取號碼
    /// </summary>
    public int PSEQ_NO { get; set; }

    /// <summary>
    /// 抽取日期
    /// </summary>
    public DateOnly TDate { get; set; }

    /// <summary>
    /// 抽取人名字
    /// </summary>
    public string LINE_NAME { get; set; }

    /// <summary>
    /// 抽取人日期
    /// </summary>
    public string LINE_TEL { get; set; }

    /// <summary>
    /// 大人(位)
    /// </summary>
    public int AD_CNT { get; set; }

    /// <summary>
    /// 小孩(位)
    /// </summary>
    public int CHI_CNT { get; set; }

    /// <summary>
    /// 狀態
    /// </summary>
    public string STATUS { get; set; }

    /// <summary>
    /// 新增人員
    /// </summary>
    public string CRT_NO { get; set; }

    /// <summary>
    /// 新增日期
    /// </summary>
    public DateTime? CRT_DATE { get; set; }

    /// <summary>
    /// 更新人員
    /// </summary>
    public string UPD_NO { get; set; }

    /// <summary>
    /// 更新日期
    /// </summary>
    public DateTime? UPD_DATE { get; set; }
}