// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class LoginVerify
{
    public string LoginEmail { get; set; }

    public string VerifyCode { get; set; }

    public DateTime MailedTime { get; set; }
}