// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class mkf001
{
    public string SUP_NO { get; set; }

    public string SU_NA { get; set; }

    public string SUN_SN { get; set; }

    public string BL_NO { get; set; }

    public string BOSS { get; set; }

    public string TELM1 { get; set; }

    public string TEL_NO { get; set; }

    public string TELM2 { get; set; }

    public string TEL_NO2 { get; set; }

    public string FAX { get; set; }

    public double? FAX_NO { get; set; }

    public double? ADD { get; set; }

    public string ADDRESS { get; set; }

    public string ACOUNT { get; set; }

    public string TYPE { get; set; }

    public string CONCET { get; set; }

    public string email { get; set; }
}