// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class mkf002
{
    public string a { get; set; }

    public string b { get; set; }

    public string c { get; set; }

    public string d { get; set; }

    public string e { get; set; }

    public string f { get; set; }

    public string g { get; set; }

    public string h { get; set; }

    public string i { get; set; }

    public string j { get; set; }

    public string k { get; set; }

    public string l { get; set; }

    public string m { get; set; }

    public string n { get; set; }

    public string o { get; set; }

    public string p { get; set; }

    public string email { get; set; }

    public string q { get; set; }
}