// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFAPP01
{
    public string COMPBLNO { get; set; }

    public string COMPNAME { get; set; }

    public string FRCOMPBLNO { get; set; }

    public string PRODUCTITEM { get; set; }

    public string COMPPERSON { get; set; }

    public string COMPZCODE { get; set; }

    public string COMPTEL { get; set; }

    public string COMPMOBILE { get; set; }

    public string COMPEMAIL { get; set; }

    public string COMPADDR { get; set; }

    public string COMPADDRCODE { get; set; }

    public string TAXNAME { get; set; }

    public string TAXSERVICENAME { get; set; }

    public string TAXID { get; set; }

    public DateTime? ENABLEDATE { get; set; }

    public string INVCOUNT { get; set; }

    public string CONTACTNAME { get; set; }

    public string CONTACTZCODE { get; set; }

    public string CONTACTTEL { get; set; }

    public string CONTACTMOBILE { get; set; }

    public string CONTACTEMAIL { get; set; }

    public string CONTACTADDRCODE { get; set; }

    public string CONTACTADDR { get; set; }

    public string ACCNAME { get; set; }

    public string ACCZCODE { get; set; }

    public string ACCTEL { get; set; }

    public string ACCMOBILE { get; set; }

    public string ACCEMAIL { get; set; }

    public string POSCOMP { get; set; }

    public string POSNAME { get; set; }

    public string POSZCODE { get; set; }

    public string POSTEL { get; set; }

    public string POSMOBILE { get; set; }

    public string ACCFIRMCOMP { get; set; }

    public string ACCFIRMBLNO { get; set; }

    public string ACCFIRMNAME { get; set; }

    public string ACCFIRMZCODE { get; set; }

    public string ACCFIRMTEL { get; set; }

    public string ACCFIRMMOBILE { get; set; }

    public string REMARK1 { get; set; }

    public string REMARK2 { get; set; }

    public string REMARK3 { get; set; }

    public string REMARK4 { get; set; }

    public string REMARK5 { get; set; }

    public string INVOICE_YN { get; set; }

    public string BRANCH_YN { get; set; }

    public string PLAACC_YN { get; set; }

    public string ADDVALUE_YN { get; set; }

    public string DOWNLOADINV_YN { get; set; }

    public string UPLOADINV_YN { get; set; }

    public string INVTYPE { get; set; }

    public string CHARGEPLAN { get; set; }

    public string CATEGORY { get; set; }

    public string DEALER { get; set; }

    public string APP_STATUS { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateOnly? Out_Date { get; set; }

    public string COMP_NO { get; set; }

    public DateTime? EMAIL_DATE { get; set; }

    public DateTime? TRANS_DATE { get; set; }

    public byte? MailRequire { get; set; }

    public byte? LineRequire { get; set; }

    public DateTime? LastMailTime { get; set; }

    public DateTime? LastLineTime { get; set; }

    public string STR_NO { get; set; }
}