// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFAPPT1
{
    public string COMPBLNO { get; set; }

    public string USUER_NAME { get; set; }

    public string USER_EMAIL { get; set; }

    public string USER_ZCODE { get; set; }

    public string USER_TEL { get; set; }

    public string USER_MOBILE { get; set; }

    public string USER_IDENTITY { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateOnly? Out_Date { get; set; }
}