// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFApiLOG
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string ECR_NO { get; set; }

    public DateTime LOG_TIME { get; set; }

    public string CONTROLLER_NAME { get; set; }

    public string METHOD_TYPE { get; set; }

    public string CLE_NO { get; set; }

    public string TABLE_NAME { get; set; }

    public string KEY_VALUE { get; set; }

    public string JSON { get; set; }

    public string ERROR_MSG { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}