// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFAPIKEY
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string API_KEY { get; set; }
}