// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFALL01
{
    public string Comp_No { get; set; }

    public string Str_No { get; set; }

    public string AllowanceNumber { get; set; }

    public DateTime AllowanceDate { get; set; }

    public string BL_NO { get; set; }

    public string buy_BL_NO { get; set; }

    public string buy_Name { get; set; }

    public string buy_Address { get; set; }

    public string buy_EMAIL { get; set; }

    public string AllowanceType { get; set; }

    public decimal Tax { get; set; }

    public decimal Tot_Amt { get; set; }

    public string CNL_YN { get; set; }

    public DateTime? CANCELDATE { get; set; }

    public string CANCELTIME { get; set; }

    public DateOnly? CnlOut_Date { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string Sys_No { get; set; }

    public DateTime? Sys_Date { get; set; }

    public DateOnly? Out_Date { get; set; }

    public string Cnl_Rea { get; set; }

    public string SENDMAIL_YN { get; set; }
}