// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFALLTI
{
    public string Comp_No { get; set; }

    public string Str_No { get; set; }

    public string AllowanceNumber { get; set; }

    public string All_SequenceNumber { get; set; }

    public string bl_no { get; set; }

    public string buy_bl_no { get; set; }

    public DateTime InvoiceDate { get; set; }

    public string INV_NO { get; set; }

    public string Inv_Desc { get; set; }

    public decimal? Qty { get; set; }

    public decimal? Price { get; set; }

    public decimal? Amt { get; set; }

    public decimal? Tax { get; set; }

    public string TaxType { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string Sys_No { get; set; }

    public DateTime? Sys_Date { get; set; }

    public decimal? ORG_Qty { get; set; }

    public decimal? ORG_Amt { get; set; }
}