// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFCLEMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string CLE_NO { get; set; }

    public string CLE_NA { get; set; }

    public string CLE_LEVEL { get; set; }

    public string CLE_PWD { get; set; }

    public string OP_YN { get; set; }

    public DateTime? CLE_DATE_B { get; set; }

    public DateTime? CLE_DATE_E { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}