// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFCMPMI
{
    public string COMP_NO { get; set; }

    public string COMP_NA { get; set; }

    public string COMP_SN { get; set; }

    public string BL_NO { get; set; }

    public string COMP_BOSS { get; set; }

    public string MCOM_BOSS { get; set; }

    public string COMP_ZTEL { get; set; }

    public string COMP_TEL { get; set; }

    public string COMP_ZTEL2 { get; set; }

    public string COMP_TEL2 { get; set; }

    public string TEL_M { get; set; }

    public string COMP_ZFAX { get; set; }

    public string COMP_FAX { get; set; }

    public string COMP_ZCODE { get; set; }

    public string COMP_ADDR { get; set; }

    public string COMP_EMAIL { get; set; }

    public string WEB_ADDR { get; set; }

    public string MEMO { get; set; }

    public DateTime? START_DATE { get; set; }

    public DateTime? END_DATE { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string CUST_TYPE { get; set; }

    public decimal? IVO_DIV_CNT { get; set; }

    public string tenant_no { get; set; }

    public string EQUIPMENT_TYPE { get; set; }

    public string LOGO_PATH { get; set; }

    public string IS_REDEEM { get; set; }

    public string TRN_EINV { get; set; }
}