// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFCompOpen_INTERFACE
{
    public int SEQ_NO { get; set; }

    public string CUST_TYPE { get; set; }

    public string COMP_NO { get; set; }

    public string COMP_NA { get; set; }

    public string COMP_SN { get; set; }

    public string MCOM_BOSS { get; set; }

    public string COMP_ZTEL { get; set; }

    public string COMP_TEL { get; set; }

    public string COMP_ZCODE { get; set; }

    public string COMP_ADDR { get; set; }

    public string STR_NO { get; set; }

    public string STR_NA { get; set; }

    public string BL_NO { get; set; }

    public string BL_NAME { get; set; }

    public DateTime? EINV_DATEB { get; set; }

    public DateTime? BDATE { get; set; }

    public DateTime? EDATE { get; set; }

    public string IVO_B { get; set; }

    public string IVO_E { get; set; }

    public string PASS_NO { get; set; }

    public string PASS_WD { get; set; }

    public string WEBSITE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? TRANS_DATE { get; set; }
}