// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFCTLSI
{
    public string COMP_NO { get; set; }

    public string CTL_CODE { get; set; }

    public string CTL_NA { get; set; }

    public string MDY_CODE { get; set; }

    public string PARA_CODE { get; set; }

    public string PARA_CHR1 { get; set; }

    public string PARA_CHR2 { get; set; }

    public decimal? PARA_NUM1 { get; set; }

    public decimal? PARA_NUM2 { get; set; }

    public DateTime? PARA_DATE1 { get; set; }

    public DateTime? PARA_DATE2 { get; set; }

    public string MEMO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}