// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBT02
{
    public string DBT_NO { get; set; }

    public string DBT_STR { get; set; }

    public string DBT_KIND { get; set; }

    public DateTime LAST_TIME { get; set; }

    public DateTime LAST_TIME_S { get; set; }

    public string CSV_NAME { get; set; }

    public string DBT_STA { get; set; }

    public string DBT_ERR_SEQ { get; set; }

    public decimal? OVR_SEQ { get; set; }

    public string DBT_ERR { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}