// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTERR
{
    public string DBT_STR { get; set; }

    public DateTime ERR_TIME { get; set; }

    public string FILE_NAME { get; set; }

    public decimal? ERR_NUMBER { get; set; }

    public string ERR_CONTENT { get; set; }

    public string ERR_MSG { get; set; }

    public decimal? ERR_ROW { get; set; }

    public DateTime? EMAIL_DATE { get; set; }
}