// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDPSMI
{
    public string COMP_NO { get; set; }

    public string DPS_NO { get; set; }

    public string DPS_NA { get; set; }

    public string DPS_SN { get; set; }

    public decimal? DPS_LEVEL { get; set; }

    public string TAX_TYPE { get; set; }

    public string TYPE_CODE { get; set; }

    public string DPD_NO { get; set; }

    public string UP_DPSNO { get; set; }

    public string UP3_DPSNO { get; set; }

    public string UP4_DPSNO { get; set; }

    public string UP5_DPSNO { get; set; }

    public string UP6_DPSNO { get; set; }

    public string UP7_DPSNO { get; set; }

    public string UP8_DPSNO { get; set; }

    public string UP9_DPSNO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }

    public string SELFSHOW { get; set; }
}