// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTPS
{
    public string Pass_No { get; set; }

    public string Pass_Na { get; set; }

    public string Pass_Wd { get; set; }

    public string Pass_Code { get; set; }

    public string Emp_No { get; set; }

    public string Pass_Type { get; set; }

    public string Spe_Code { get; set; }

    public string E_Mail { get; set; }

    public string Str_No { get; set; }

    public DateTime? Start_Date { get; set; }

    public DateTime? End_Date { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}