// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTEO
{
    public string DBT_STR { get; set; }

    public string DBT_SEQ { get; set; }

    public string ECO_TYPE { get; set; }

    public string ECO_MSG { get; set; }

    public DateTime ECO_TIME { get; set; }

    public decimal ECO_SEC { get; set; }

    public DateTime VER_TIME { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}