// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTC1
{
    public string Comm_No { get; set; }

    public string Code_No { get; set; }

    public string Code_Txt { get; set; }

    public string Para_Code { get; set; }

    public string Para_Chr1 { get; set; }

    public string Para_Chr2 { get; set; }

    public string Para_Chr3 { get; set; }

    public decimal? Para_Num1 { get; set; }

    public decimal? Para_Num2 { get; set; }

    public decimal? Para_Num3 { get; set; }

    public DateTime? Para_Date1 { get; set; }

    public DateTime? Para_Date2 { get; set; }

    public DateTime? Para_Date3 { get; set; }

    public string DEL_YN { get; set; }

    public string Memo { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}