// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTC0
{
    public string Comm_No { get; set; }

    public string Comm_Na { get; set; }

    public string Sys_ID { get; set; }

    public decimal? Code_Len { get; set; }

    public decimal? Text_Len { get; set; }

    public string Blg_Grp { get; set; }

    public string Mdy_code { get; set; }

    public string Memo { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string Prog_No { get; set; }

    public string Prog_Id { get; set; }

    public string Table_Na { get; set; }

    public string Field_Na { get; set; }
}