// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTMI
{
    public string DBT_NO { get; set; }

    public string DBT_STR { get; set; }

    public string DBT_SEQ { get; set; }

    public string DBT_KIND { get; set; }

    public string FILE_NAME_O { get; set; }

    public decimal? CSV_BYTES { get; set; }

    public decimal? ROW_NUM { get; set; }

    public DateTime? DBT_TIMEB { get; set; }

    public DateTime? DBT_TIMEE { get; set; }

    public DateTime? CSV_TIMEB { get; set; }

    public DateTime? CSV_TIMEE { get; set; }

    public DateTime? DBT_ERRTIME_O { get; set; }

    public string DBT_ERR_O { get; set; }

    public string SUCESS_YN_O { get; set; }

    public decimal? OVR_SEQ_O { get; set; }

    public string FILE_NAME_R { get; set; }

    public decimal? INS_ROW { get; set; }

    public decimal? INS_BEFORE_ROW { get; set; }

    public decimal? INS_AFTER_ROW { get; set; }

    public DateTime? INS_BEFORE_TIMEB { get; set; }

    public DateTime? INS_BEFORE_TIMEE { get; set; }

    public DateTime? INS_AFTER_TIMEB { get; set; }

    public DateTime? INS_AFTER_TIMEE { get; set; }

    public DateTime? DBT_ERRTIME_I { get; set; }

    public string DBT_ERR_I { get; set; }

    public string SUCESS_YN_I { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}