// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBT01
{
    public string DBT_NO { get; set; }

    public string DBT_STR { get; set; }

    public string DBT_YN { get; set; }

    public decimal DBT_ORDER { get; set; }

    public string DBT_TYPE { get; set; }

    public string DBT_NAME { get; set; }

    public string DST_TABLE { get; set; }

    public string DBT_CMD { get; set; }

    public string UPD_TYPE { get; set; }

    public string SCH_TYPE { get; set; }

    public string SCH_PSECD { get; set; }

    public string SCH_PTIME { get; set; }

    public decimal? ROW_COMMIT { get; set; }

    public decimal? OVR_SECD { get; set; }

    public decimal? OVR_CNT { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_DATE { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_DATE { get; set; }
}