// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTCD
{
    public string DBT_NO { get; set; }

    public string DBT_STR { get; set; }

    public string INS_KIND { get; set; }

    public decimal INS_ORDER { get; set; }

    public string INS_CMD { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}