// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFDBTEM
{
    public string DBT_STR { get; set; }

    public string SEQ_NO { get; set; }

    public DateTime TIME_B { get; set; }

    public DateTime TIME_E { get; set; }

    public string SRC_PATH { get; set; }

    public string DST_PATH { get; set; }

    public string SRC_FILE { get; set; }

    public string DST_FILE { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }
}