// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFECR01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime TDATE { get; set; }

    public string ECR_NO { get; set; }

    public decimal DEAL_NO { get; set; }

    public DateTime? TTIME { get; set; }

    public string CLE_NO { get; set; }

    public DateTime? ORG_TDATE { get; set; }

    public decimal? ORG_DEAL_NO { get; set; }

    public DateTime? ORG_TTIME { get; set; }

    public string DEAL_CODE { get; set; }

    public string DEAL_MODE { get; set; }

    public string OV_ECP_TYPE { get; set; }

    public decimal? DIS_AMT { get; set; }

    public decimal? MIN_AMT { get; set; }

    public decimal? DISAMT_01 { get; set; }

    public decimal? MINAMT_01 { get; set; }

    public decimal? OVER_AMT { get; set; }

    public decimal? TOT_AMT { get; set; }

    public decimal? STAX_AMT { get; set; }

    public decimal? ZEROTAX_AMT { get; set; }

    public decimal? NOTAX_AMT { get; set; }

    public decimal? TAXED_AMT { get; set; }

    public decimal? TAX_AMT { get; set; }

    public string SALER_NO { get; set; }

    public string DEAL_CHANGE_YN { get; set; }

    public string DEL_CLE_NO { get; set; }

    public DateTime? DEL_TTIME { get; set; }

    public string INV_TYPE { get; set; }

    public decimal? INV_CNT { get; set; }

    public string CARD_NO { get; set; }

    public string CUST_LEVEL { get; set; }

    public string BAG_CODE { get; set; }

    public string STAMP_CODE { get; set; }

    public decimal? HT_AMT { get; set; }

    public decimal? PTS_SAMT { get; set; }

    public decimal? TPTS_SAMT { get; set; }

    public decimal? SBPTS { get; set; }

    public string SETTING_NO { get; set; }

    public string SETTING_MEMO { get; set; }

    public string TAC_CODE { get; set; }

    public DateTime? TAC_DATE { get; set; }

    public string TAC_NO { get; set; }

    public string MEMO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? EINV_DATE { get; set; }

    public string TABLE_NO { get; set; }

    public string ADDR_CITY { get; set; }

    public string ADDR_DISTRICT { get; set; }

    public string ADDR_ROAD { get; set; }

    public string ADDR_OTHER { get; set; }

    public decimal? SEQ_NO { get; set; }

    public string USE_NA { get; set; }

    public string VIP_NO { get; set; }

    public string VIP_NA { get; set; }

    public string TEL_M { get; set; }

    public string PLW_ID { get; set; }

    public string ISC_REDEEM { get; set; }
}