// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFECRFI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime TDATE { get; set; }

    public string ECR_NO { get; set; }

    public decimal DEAL_NO { get; set; }

    public decimal ITEM_NO { get; set; }

    public string INV_NO { get; set; }

    public string INV_TYPE { get; set; }

    public string TAX_TYPE { get; set; }

    public string BL_NO { get; set; }

    public decimal? TOT_AMT { get; set; }

    public decimal? ZEROTAX_AMT { get; set; }

    public decimal? NOTAX_AMT { get; set; }

    public decimal? TAXED_AMT { get; set; }

    public decimal? TAX_AMT { get; set; }

    public string CANCEL_YN { get; set; }

    public DateTime? CANCEL_DATE { get; set; }

    public decimal? HT_AMT { get; set; }

    public string DONATE_MARK { get; set; }

    public string CARRY_TYPE { get; set; }

    public string CARRY_ID { get; set; }

    public string CARRY_ID2 { get; set; }

    public string PRINT_YN { get; set; }

    public DateTime? PRINT_DATE { get; set; }

    public string MOBILE_CODE { get; set; }

    public string LOVE_CODE { get; set; }

    public string RANDOM_CODE { get; set; }

    public decimal? PLIST_CNT { get; set; }

    public string PINV_CODE { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? EINV_DATE { get; set; }
}