// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFEcr_INTERFACE
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime TDATE { get; set; }

    public string ECR_NO { get; set; }

    public decimal DEAL_NO { get; set; }

    public string INV_NO { get; set; }

    public string APPLY_CODE { get; set; }

    public string STATUS { get; set; }

    public DateTime APPLY_DATE { get; set; }

    public DateTime? CONFIRM_DATE { get; set; }

    public DateTime? FINISH_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }
}