// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFECRPI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime TDATE { get; set; }

    public string ECR_NO { get; set; }

    public decimal DEAL_NO { get; set; }

    public decimal PAY_ITEM { get; set; }

    public string CLE_NO { get; set; }

    public string DEAL_CODE { get; set; }

    public string ECP_TYPE { get; set; }

    public string ECP_NO { get; set; }

    public decimal? ECP_AMT { get; set; }

    public decimal? OVER_AMT { get; set; }

    public decimal? BPTS { get; set; }

    public decimal? LBPTS { get; set; }

    public decimal? TBPTS { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? EINV_DATE { get; set; }

    public string TAXED_YN { get; set; }
}