// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFECROP
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string ECR_NO { get; set; }

    public decimal DEAL_NO { get; set; }

    public DateTime TDATE { get; set; }

    public DateTime OP_TIME { get; set; }

    public decimal? DEAL_ITEM { get; set; }

    public string CLE_NO { get; set; }

    public string OP_TYPE { get; set; }

    public string PLU_NO { get; set; }

    public string GOO_NO { get; set; }

    public decimal? SPRICE { get; set; }

    public decimal? QTY { get; set; }

    public decimal? DIS_AMT { get; set; }

    public decimal? MIN_AMT { get; set; }

    public decimal? DIS_PER { get; set; }

    public decimal? TOT_AMT { get; set; }

    public string CARD_NO { get; set; }

    public string CARD_TYPE { get; set; }

    public string GIF_NO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string MEMO { get; set; }
}