// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFECPMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string ECP_TYPE { get; set; }

    public string ECP_NA { get; set; }

    public string OVER_FLAG { get; set; }

    public decimal? OVER_MAX_AMT { get; set; }

    public string TAXED_YN { get; set; }

    public string QUANTITY_YN { get; set; }

    public string REPEAT_YN { get; set; }

    public string VOUCHERNO_YN { get; set; }

    public string CONNECT_YN { get; set; }

    public string CARDNO_PRT_YN { get; set; }

    public string APPROVE_YN { get; set; }

    public string APPROVE_PRT_YN { get; set; }

    public string VOUCHER_PRT_YN { get; set; }

    public string USE_YN { get; set; }

    public string MEMO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string BUSINESS_YN { get; set; }
}