// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFECRTI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime TDATE { get; set; }

    public string ECR_NO { get; set; }

    public decimal DEAL_NO { get; set; }

    public decimal DEAL_ITEM { get; set; }

    public string PLU_NO { get; set; }

    public DateTime? TTIME { get; set; }

    public string GOO_NO { get; set; }

    public string CLE_NO { get; set; }

    public string DEAL_CODE { get; set; }

    public string OP_TYPE { get; set; }

    public string DPS_NO { get; set; }

    public decimal? GOO_SPRICE { get; set; }

    public decimal? SPRICE { get; set; }

    public decimal? QTY { get; set; }

    public string DIS_TYPE { get; set; }

    public decimal? DIS_AMT { get; set; }

    public decimal? MIN_AMT { get; set; }

    public decimal? DIS_RATE { get; set; }

    public decimal? TOT_AMT { get; set; }

    public decimal? MIN_AMT1 { get; set; }

    public decimal? MIN_AMT2 { get; set; }

    public decimal? DPC_RATE { get; set; }

    public string TAX_TYPE { get; set; }

    public decimal? TAX_AMT { get; set; }

    public decimal? TAX_RATE { get; set; }

    public decimal? HT_PRICE { get; set; }

    public decimal? HT_AMT { get; set; }

    public string PNO_NO { get; set; }

    public string PRS_TYPE { get; set; }

    public string PRS_NO { get; set; }

    public decimal? ACL_DPTS { get; set; }

    public decimal? ACL_LDPTS { get; set; }

    public decimal? ACL_TDPTS { get; set; }

    public decimal? ACL_GDPTS { get; set; }

    public string GOO_NAME { get; set; }

    public string PRT_DATA { get; set; }

    public string MEMO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public DateTime? EINV_DATE { get; set; }
}