// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFGOOMI
{
    public string COMP_NO { get; set; }

    public string GOO_NO { get; set; }

    public string GOO_NA { get; set; }

    public string SUB_NA { get; set; }

    public string PLU_CD { get; set; }

    public string PLU_NO { get; set; }

    public string DPS_NO { get; set; }

    public string DPD_NO { get; set; }

    public string TAX_TYPE { get; set; }

    public decimal? ITAX_RATE { get; set; }

    public decimal? STAX_RATE { get; set; }

    public string BUNT_NA { get; set; }

    public string SUNT_NA { get; set; }

    public decimal? SAFE_QTY { get; set; }

    public decimal? SALE_QTY { get; set; }

    public decimal? BPCK_QTY { get; set; }

    public decimal? SPCK_QTY { get; set; }

    public decimal? SPRICE { get; set; }

    public decimal? B_SPRICE { get; set; }

    public decimal? B_IPRICE { get; set; }

    public string TENANT_YN { get; set; }

    public string SUP_NO { get; set; }

    public string SUP_GOONO { get; set; }

    public decimal? IPRICE { get; set; }

    public decimal? TAX_IPRICE { get; set; }

    public decimal? BAS_PUR { get; set; }

    public decimal? PUR_BAS { get; set; }

    public decimal? PUR_PN1 { get; set; }

    public decimal? PUR_PN2 { get; set; }

    public string PUR_PGOO { get; set; }

    public string PUR_TYPE { get; set; }

    public string DEL_TYPE { get; set; }

    public DateTime? DEL_DATE { get; set; }

    public string GOO_TYPE { get; set; }

    public string PC_CHAR { get; set; }

    public string GOO_SCODE { get; set; }

    public string SEASON { get; set; }

    public string STOP_PUR { get; set; }

    public string STOP_RJI { get; set; }

    public string STOP_SAL { get; set; }

    public string DIS_YN { get; set; }

    public string BPRS_YN { get; set; }

    public string TECR_YN { get; set; }

    public string PTS_YN { get; set; }

    public string LABEL_YN { get; set; }

    public string KC_PRINT_YN { get; set; }

    public string KC_PRINTER { get; set; }

    public string SET_YN { get; set; }

    public decimal? DMS_QTY { get; set; }

    public decimal? M_DMS_QTY { get; set; }

    public DateTime? NEW_IDATE { get; set; }

    public DateTime? IDATE { get; set; }

    public DateTime? SDATE { get; set; }

    public DateTime? PDATE { get; set; }

    public decimal? AVPRICE { get; set; }

    public decimal? TAX_AVPRICE { get; set; }

    public decimal? AVPRICE2 { get; set; }

    public decimal? TAX_AVPRICE2 { get; set; }

    public decimal? YQTY { get; set; }

    public decimal? YAMT { get; set; }

    public decimal? YTAX_AMT { get; set; }

    public decimal? QTY { get; set; }

    public decimal? AMT { get; set; }

    public decimal? TAX_AMT { get; set; }

    public decimal? ON_QTY { get; set; }

    public decimal? ON_AMT { get; set; }

    public decimal? ONTAX_AMT { get; set; }

    public string MEMO { get; set; }

    public string OK_YN { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }

    public string UPL_STATUS { get; set; }

    public DateTime? UPL_DATE { get; set; }

    public string FILENAME { get; set; }

    public string FILE_PATH { get; set; }

    public string ORG_YN { get; set; }

    public string SOURCE_PROG { get; set; }

    public string RecType { get; set; }

    public string RecMEMO { get; set; }

    public string SET_TYPE { get; set; }

    public string GROUP_YN { get; set; }

    public decimal? SPRICE_B2B { get; set; }
}