// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFGOO_BZX
{
    public string GOO_NO { get; set; }

    public string GOO_NA { get; set; }

    public double? SPRICE { get; set; }
}