// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFGOSMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string GOO_NO { get; set; }

    public string SUP_NO { get; set; }

    public decimal? IPRICE { get; set; }

    public decimal? TAX_IPRICE { get; set; }

    public decimal? BAS_PUR { get; set; }

    public decimal? PUR_BAS { get; set; }

    public decimal? PUR_PN1 { get; set; }

    public decimal? PUR_PN2 { get; set; }

    public string PUR_PGOO { get; set; }

    public decimal? SAFE_QTY { get; set; }

    public decimal? SPRICE { get; set; }

    public string DEL_TYPE { get; set; }

    public DateTime? DEL_DATE { get; set; }

    public string STOP_PUR { get; set; }

    public string STOP_RJI { get; set; }

    public string STOP_SAL { get; set; }

    public string DIS_YN { get; set; }

    public string BPRS_YN { get; set; }

    public string TECR_YN { get; set; }

    public string PTS_YN { get; set; }

    public string LABEL_YN { get; set; }

    public string KC_PRINT_YN { get; set; }

    public string KC_PRINTER { get; set; }

    public string SET_YN { get; set; }

    public string M_IPRSNO { get; set; }

    public string M_PNONO { get; set; }

    public DateTime? M_IBDD { get; set; }

    public DateTime? M_IEDD { get; set; }

    public decimal? M_IPRICE { get; set; }

    public decimal? M_TAX_IPRICE { get; set; }

    public decimal? M_PN1 { get; set; }

    public decimal? M_PN2 { get; set; }

    public string M_PGOO { get; set; }

    public DateTime? M_SBDD { get; set; }

    public DateTime? M_SEDD { get; set; }

    public string PRO_TYPE { get; set; }

    public string PRS_NO { get; set; }

    public decimal? M_SPRICE { get; set; }

    public string VPRO_TYPE { get; set; }

    public string VPRS_NO { get; set; }

    public decimal? M_VSPRICE { get; set; }

    public string SALE_YN { get; set; }

    public decimal? DMS_QTY { get; set; }

    public decimal? M_DMS_QTY { get; set; }

    public DateTime? NEW_IDATE { get; set; }

    public DateTime? IDATE { get; set; }

    public DateTime? SDATE { get; set; }

    public DateTime? PDATE { get; set; }

    public string M_SUPNO { get; set; }

    public string INP_SUPNO { get; set; }

    public decimal? INP_IPRICE { get; set; }

    public decimal? INP_TAX_IPRICE { get; set; }

    public decimal? AVPRICE { get; set; }

    public decimal? TAX_AVPRICE { get; set; }

    public decimal? AVPRICE2 { get; set; }

    public decimal? TAX_AVPRICE2 { get; set; }

    public decimal? YQTY { get; set; }

    public decimal? YAMT { get; set; }

    public decimal? YTAX_AMT { get; set; }

    public decimal? QTY { get; set; }

    public decimal? AMT { get; set; }

    public decimal? TAX_AMT { get; set; }

    public decimal? ON_QTY { get; set; }

    public decimal? ON_AMT { get; set; }

    public decimal? ONTAX_AMT { get; set; }

    public decimal? SDAYS { get; set; }

    public decimal? DDAYS { get; set; }

    public decimal? IDAYS { get; set; }

    public string MEMO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }

    public string IsWebOrder { get; set; }

    public decimal? SPRICE_B2B { get; set; }
}