// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFINVMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string INV_PERIOD { get; set; }

    public string INV_BNO { get; set; }

    public string INV_ENO { get; set; }

    public string INV_CNO { get; set; }

    public DateOnly? INV_BDATE { get; set; }

    public DateOnly? INV_EDATE { get; set; }

    public string INVOICETYPE { get; set; }

    public string INV_TYPE { get; set; }

    public string DEL_FLAG { get; set; }

    public DateTime? DEL_DATE { get; set; }

    public string DEL_NO { get; set; }

    public string OK_YN { get; set; }

    public string OK_NO { get; set; }

    public DateTime? OK_DATE { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }
}