// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFINVTI
{
    public string Comp_No { get; set; }

    public string Str_No { get; set; }

    public DateOnly Kdate { get; set; }

    public decimal Seq_No { get; set; }

    public decimal Item_No { get; set; }

    public string Inv_Desc_NO { get; set; }

    public string Inv_Desc { get; set; }

    public string Tax_Type { get; set; }

    public decimal? Qty { get; set; }

    public decimal? Price { get; set; }

    public decimal? Amt { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string Sys_No { get; set; }

    public DateTime? Sys_Date { get; set; }

    public decimal? TAX { get; set; }
}