// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFINVGOO
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string GOO_NO { get; set; }

    public string GOO_NA { get; set; }

    public string PLU_CD { get; set; }

    public string PLU_NO { get; set; }

    public string TAX_TYPE { get; set; }

    public decimal? ITAX_RATE { get; set; }

    public decimal? STAX_RATE { get; set; }

    public decimal? SPRICE { get; set; }

    public decimal? IPRICE { get; set; }

    public decimal? TAX_IPRICE { get; set; }

    public string MEMO { get; set; }

    public string OK_YN { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string DEL_TYPE { get; set; }
}