// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFINVBL
{
    public string Comp_No { get; set; }

    public string Buy_Bl_No { get; set; }

    public string Buy_Na { get; set; }

    public string Buy_Zone_Code { get; set; }

    public string Buy_Address { get; set; }

    public string Buy_E_Mail { get; set; }

    public string Buy_Ztel { get; set; }

    public string Buy_Tel { get; set; }

    public string Buy_Ztel2 { get; set; }

    public string Buy_Tel2 { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string Sys_No { get; set; }

    public DateTime? Sys_Date { get; set; }

    public string STR_NO { get; set; }
}