// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFINVCOUNT
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public DateTime TDATE { get; set; }

    public decimal? INV_effective { get; set; }

    public decimal? INV_invalid { get; set; }

    public decimal? AMT_effective { get; set; }

    public decimal? AMT_invalid { get; set; }

    public DateTime? TTIME { get; set; }

    public DateTime? EINV_DATE { get; set; }

    public DateTime? DEL_TTIME { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}