// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFINV01
{
    public string Comp_No { get; set; }

    public string Str_No { get; set; }

    public DateOnly Kdate { get; set; }

    public decimal Seq_No { get; set; }

    public string Inv_No { get; set; }

    public string Inv_type { get; set; }

    public DateOnly? Inv_Date { get; set; }

    public DateTime? Inv_Time { get; set; }

    public string Tax_Type { get; set; }

    public string check_no { get; set; }

    public string buy_bl_no { get; set; }

    public string buy_na { get; set; }

    public string buy_Address { get; set; }

    public string buy_EMAIL { get; set; }

    public decimal? Stax_Amt { get; set; }

    public decimal? Tax { get; set; }

    public decimal? ZeroTax_Amt { get; set; }

    public decimal? Notax_Amt { get; set; }

    public decimal? Tot_Amt { get; set; }

    public string MIG_Type { get; set; }

    public DateOnly? App_date { get; set; }

    public string Donate_Mark { get; set; }

    public string Love_Code { get; set; }

    public string Carry_Type { get; set; }

    public string Carry_Id { get; set; }

    public string Carry_Id1 { get; set; }

    public string Carry_Id2 { get; set; }

    public string Print_Yn { get; set; }

    public DateOnly? Print_Date { get; set; }

    public string NPOBAN { get; set; }

    public string Random_Code { get; set; }

    public decimal? PList_Cnt { get; set; }

    public string Cnl_Yn { get; set; }

    public DateOnly? Cnl_Date { get; set; }

    public DateTime? Cnl_Time { get; set; }

    public string Cnl_Rea { get; set; }

    public DateOnly? Out_Date { get; set; }

    public string Out_FNa { get; set; }

    public string Memo { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string BL_NO { get; set; }

    public DateTime? TRANS_DATE { get; set; }

    public DateTime? TRANS_CDATE { get; set; }

    public string ORDER_NO { get; set; }

    public string BUY_MOBILE { get; set; }

    public DateTime? cnlout_date { get; set; }

    public string ECP_TYPE { get; set; }

    public decimal? TAXED_AMT { get; set; }
}