// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFIVONO_LOG
{
    public long ID { get; set; }

    public string MOD_TYPE { get; set; }

    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string ECR_NO { get; set; }

    public string IVO_B { get; set; }

    public string IVO_E { get; set; }

    public DateTime BDATE { get; set; }

    public DateTime? EDATE { get; set; }

    public string CURRENT_IVO { get; set; }

    public decimal? IVO_CNT { get; set; }

    public string FLAG { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string IN_USE { get; set; }

    public string IP { get; set; }

    public string Ok_No { get; set; }

    public string Ok_Pwd { get; set; }

    public string Del_Flg { get; set; }

    public string Del_No { get; set; }

    public string Del_Pwd { get; set; }

    public DateTime? Ok_Date { get; set; }

    public DateTime? Del_Date { get; set; }
}