// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class mkfmnumi_new
{
    public string COMP_NO { get; set; }

    public string MNU_NO { get; set; }

    public decimal ITEM_NO { get; set; }

    public string SYS_ID { get; set; }

    public string PROG_NO { get; set; }

    public string PROG_ID { get; set; }

    public string PROG_NA { get; set; }

    public string MNU_TYPE { get; set; }

    public string SD { get; set; }

    public DateTime? SD_DATE { get; set; }

    public string PG { get; set; }

    public DateTime? PG_DATE { get; set; }

    public string PG_OK { get; set; }

    public string UPL_OK { get; set; }

    public string STR_TYPE { get; set; }

    public string MEMO { get; set; }

    public string CLT_OK { get; set; }

    public decimal? MAXQUCNT { get; set; }

    public string USER_ITEM { get; set; }

    public string HELPME { get; set; }

    public string URL_PATH { get; set; }

    public string RUN_DAY { get; set; }

    public string RUN_WDAY { get; set; }

    public string RUN_TIME_E { get; set; }

    public string RUN_TIME_B { get; set; }

    public string PROG_NA_CN { get; set; }

    public string PROG_NA_EN { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}