// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class mkfnews01
{
    public string news_no { get; set; }

    public DateOnly? news_bdate { get; set; }

    public DateOnly? news_edate { get; set; }

    public string news_title { get; set; }

    public string content { get; set; }

    public string upd_no { get; set; }

    public string str_all { get; set; }

    public string ok_yn { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime crt_date { get; set; }

    public string ann_no { get; set; }
}