// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFPOS01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string ECR_NO { get; set; }

    public string ECR_NA { get; set; }

    public string BTN_TYPE { get; set; }

    public string USE_YN { get; set; }

    public string MEMO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string DEVICE_NO { get; set; }

    public string SN { get; set; }
}