// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFPOSMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string ECR_NO { get; set; }

    public string POS_CTL_CODE { get; set; }

    public string POS_CTL_NA { get; set; }

    public string POS_PARA_CHR1 { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}