// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFPLUMI
{
    public string COMP_NO { get; set; }

    public string PLU_NO { get; set; }

    public string GOO_NO { get; set; }

    public string PLU_CD { get; set; }

    public string DEL_TYPE { get; set; }

    public DateTime? DEL_DATE { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }
}