// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFSED00
{
    public string cate1 { get; set; }

    public string pad_chr { get; set; }

    public string cate1_na { get; set; }

    public decimal? mnos { get; set; }

    public decimal? mnoe { get; set; }

    public decimal? mno_step { get; set; }

    public string cycle { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime? crt_date { get; set; }
}