// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFSEQMI
{
    public string COMP_NO { get; set; }

    public string Str_No { get; set; }

    public string Kind_No { get; set; }

    public DateTime TDate { get; set; }

    public decimal? Seq_No { get; set; }

    public string Cir_Code { get; set; }

    public string Upd_No { get; set; }

    public DateTime? Upd_Date { get; set; }

    public string Crt_No { get; set; }

    public DateTime? Crt_Date { get; set; }

    public string Seq_Lead { get; set; }

    public decimal? Seq_Len { get; set; }
}