// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFSTRMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string STR_NA { get; set; }

    public string STR_SN { get; set; }

    public string STR_PATTERN { get; set; }

    public string UP_ORG_NO { get; set; }

    public string LEADER { get; set; }

    public string BL_NO { get; set; }

    public string TEL_ZNO { get; set; }

    public string TEL_NO { get; set; }

    public string FAX_ZNO { get; set; }

    public string FAX_NO { get; set; }

    public string STR_ZCODE { get; set; }

    public string STR_ADDR { get; set; }

    public string E_MAIL { get; set; }

    public DateTime? OPEN_DATE { get; set; }

    public DateTime? CLOSE_DATE { get; set; }

    public DateTime? EINV_DATEB { get; set; }

    public DateTime? EINV_DATEE { get; set; }

    public string EINV_CHARGETYPE { get; set; }

    public decimal? EINV_RENT { get; set; }

    public decimal? EINV_PRICE { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string BL_NAME { get; set; }

    public string TAX_IDENTIFIER { get; set; }

    public DateTime? B2B_EINV_DATEB { get; set; }

    public DateTime? B2B_EINV_DATEE { get; set; }

    public string BL_STR_NO { get; set; }

    public string TRN_E0402 { get; set; }

    public string TRN_INVOICE { get; set; }

    public string BL_NO_HEAD { get; set; }

    public string EMAIL_YN { get; set; }

    public string PRIZE_YN { get; set; }
}