// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFSUPMI
{
    public string COMP_NO { get; set; }

    public string SUP_NO { get; set; }

    public string SUP_NA { get; set; }

    public string SUP_SN { get; set; }

    public string TAXSUP_YN { get; set; }

    public string MAIN_MEMO { get; set; }

    public string SUP_LEVEL { get; set; }

    public string BL_NO { get; set; }

    public string SUP_BLNO { get; set; }

    public string UP_SUPNO { get; set; }

    public string DEL_TYPE { get; set; }

    public DateTime? DEL_DATE { get; set; }

    public string COMP_BOSS { get; set; }

    public string COMP_TIL { get; set; }

    public string MCOM_BOSS { get; set; }

    public string MCOM_TIL { get; set; }

    public string COMP_ZTEL { get; set; }

    public string COMP_TEL { get; set; }

    public string COMP_ZTEL2 { get; set; }

    public string COMP_TEL2 { get; set; }

    public string COMP_ZFAX { get; set; }

    public string COMP_FAX { get; set; }

    public string COMP_ZCODE { get; set; }

    public string COMP_ADDR { get; set; }

    public string COMP_EMAIL { get; set; }

    public string WEB_IP { get; set; }

    public string OCOM_BOSS { get; set; }

    public string OCOM_TIL { get; set; }

    public string OCOM_ZTEL { get; set; }

    public string OCOM_TEL { get; set; }

    public string OCOM_ZTEL2 { get; set; }

    public string OCOM_TEL2 { get; set; }

    public string OCOM_ZFAX { get; set; }

    public string OCOM_FAX { get; set; }

    public string OCOM_ZCODE { get; set; }

    public string OCOM_ADDR { get; set; }

    public string OCOM_EMAIL { get; set; }

    public string AUTO_ZFAX { get; set; }

    public string AUTO_FAX { get; set; }

    public string RCOM_BOSS { get; set; }

    public string RCOM_TIL { get; set; }

    public string RCOM_ZTEL { get; set; }

    public string RCOM_TEL { get; set; }

    public string RCOM_ZTEL2 { get; set; }

    public string RCOM_TEL2 { get; set; }

    public string RCOM_ZFAX { get; set; }

    public string RCOM_FAX { get; set; }

    public string RCOM_ZCODE { get; set; }

    public string RCOM_ADDR { get; set; }

    public string RCOM_EMAIL { get; set; }

    public string RJI_TYPE { get; set; }

    public string PCOM_BOSS { get; set; }

    public string PCOM_TIL { get; set; }

    public string PCOM_ZTEL { get; set; }

    public string PCOM_TEL { get; set; }

    public string PCOM_ZTEL2 { get; set; }

    public string PCOM_TEL2 { get; set; }

    public string PCOM_ZFAX { get; set; }

    public string PCOM_FAX { get; set; }

    public string PCOM_ZCODE { get; set; }

    public string PCOM_ADDR { get; set; }

    public string PCOM_EMAIL { get; set; }

    public string PTY_NO { get; set; }

    public string PTY_CD { get; set; }

    public string IVO_TYPE { get; set; }

    public string SUP_BANK { get; set; }

    public string SUP_ACNO { get; set; }

    public string SUP_ACNA { get; set; }

    public string PAY_NA { get; set; }

    public string SUP_TYPE { get; set; }

    public string PUR_LOW { get; set; }

    public decimal? MIN_PUR { get; set; }

    public decimal? MAX_PUR { get; set; }

    public decimal? LEAD_DAY { get; set; }

    public string WEEK01 { get; set; }

    public string WEEK02 { get; set; }

    public string WEEK03 { get; set; }

    public string WEEK04 { get; set; }

    public string WEEK05 { get; set; }

    public string WEEK06 { get; set; }

    public string WEEK07 { get; set; }

    public string WEEK11 { get; set; }

    public string WEEK12 { get; set; }

    public string WEEK13 { get; set; }

    public string WEEK14 { get; set; }

    public string WEEK15 { get; set; }

    public string WEEK16 { get; set; }

    public string WEEK17 { get; set; }

    public string SEND_TYPE { get; set; }

    public string ORDER_TYPE { get; set; }

    public string INFORM_TYPE { get; set; }

    public string STOP_USE { get; set; }

    public string STOP_PUR { get; set; }

    public string STOP_RJI { get; set; }

    public string STOP_PAY { get; set; }

    public string RJI_TP { get; set; }

    public string DPD_NO { get; set; }

    public string TENANT_YN { get; set; }

    public string TOSUM_YN { get; set; }

    public string MSUP_YN { get; set; }

    public string EINV_UCODE { get; set; }

    public string OSUP_NO { get; set; }

    public DateTime? START_DATE { get; set; }

    public DateTime? LAST_INPD { get; set; }

    public DateTime? LAST_RJID { get; set; }

    public DateTime? LAST_PAYC { get; set; }

    public DateTime? LAST_PAYD { get; set; }

    public string MEMO { get; set; }

    public string OK_YN { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }
}