// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFTRCW4
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string PASS_NO { get; set; }

    public string PROG_NO { get; set; }

    public string PROG_ID { get; set; }

    public DateTime? RUN_TIME { get; set; }

    public DateTime? LOG_TIME { get; set; }

    public string SEC { get; set; }

    public string LOG_CODE { get; set; }
}