// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFTRC01
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string PASS_NO { get; set; }

    public string PROG_NO { get; set; }

    public string PROG_ID { get; set; }

    public DateTime RUN_TIME { get; set; }

    public DateTime? END_TIME { get; set; }

    public string STATUS { get; set; }

    public decimal? CNT { get; set; }

    public decimal? RET { get; set; }

    public string PARA_IN { get; set; }

    public string PARA_OUT { get; set; }

    public decimal? SPID { get; set; }

    public string DB_USER { get; set; }

    public string DB_HOST { get; set; }
}