// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class MKFVersion
{
    public decimal Id { get; set; }

    public string AppName { get; set; }

    public string Version { get; set; }

    public string FilePath { get; set; }
}