// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class ORDERSHOPEE
{
    public string COMP_NO { get; set; }

    public string ORDER_NO { get; set; }

    public string BUY_ACCOUNT { get; set; }

    public DateTime? ORDERDATE { get; set; }

    public decimal? PRODUCTAMT { get; set; }

    public decimal? BUY_TOTAMT { get; set; }

    public decimal? BUYFREIGHT { get; set; }

    public decimal? SHOPEEFREIGHT { get; set; }

    public decimal? RETURNFREIGHT { get; set; }

    public decimal? SHOPEEDIS { get; set; }

    public decimal? BANKDIS { get; set; }

    public string COUPONNUMBER { get; set; }

    public decimal? SHOPEECOUPON { get; set; }

    public decimal? SELLERCOUPON { get; set; }

    public decimal? COUPON { get; set; }

    public decimal? HANDFEE { get; set; }

    public decimal? SERVICEFEE { get; set; }

    public decimal? CASHSERVICEFEE { get; set; }

    public decimal? INSTALLMENT { get; set; }

    public decimal? HANDFEERATE { get; set; }

    public string STATE { get; set; }

    public string REASON { get; set; }
}