// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class POSZIPCODE
{
    public string ZIPCODE { get; set; }

    public string CITY { get; set; }

    public string AREA { get; set; }

    public string ROAD { get; set; }

    public string DETAIL { get; set; }
}