// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSBATPRTTI
{
    public string comp_no { get; set; }

    public int Id { get; set; }

    /// <summary>
    /// 主檔ID
    /// </summary>
    public int MId { get; set; }

    /// <summary>
    /// 對應選單程式ID
    /// </summary>
    public int MnuId { get; set; }

    /// <summary>
    /// 目錄排序用編號
    /// </summary>
    public string SortNo { get; set; }

    /// <summary>
    /// 目錄縮排
    /// </summary>
    public int Level { get; set; }

    /// <summary>
    /// 目錄起頁碼
    /// </summary>
    public int PagesStart { get; set; }

    /// <summary>
    /// 目錄迄頁碼
    /// </summary>
    public int PagesEnd { get; set; }

    /// <summary>
    /// 留白頁數
    /// </summary>
    public int JumpPages { get; set; }

    /// <summary>
    /// 是否列印
    /// </summary>
    public string EnablePrint { get; set; }

    /// <summary>
    /// 是否顯示於目錄
    /// </summary>
    public string ShowOnList { get; set; }

    public string ParameterJson { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime? crt_date { get; set; }
}