// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSBATPRTMI
{
    public string comp_no { get; set; }

    public int Id { get; set; }

    /// <summary>
    /// 名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 查詢用年度
    /// </summary>
    public string Year { get; set; }

    /// <summary>
    /// 查詢用月份
    /// </summary>
    public string Month { get; set; }

    /// <summary>
    /// 查詢用部門
    /// </summary>
    public string DeptNo { get; set; }

    /// <summary>
    /// 查詢用階段別
    /// </summary>
    public string Stage { get; set; }

    /// <summary>
    /// 查詢用作者
    /// </summary>
    public string UserNo { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime? crt_date { get; set; }
}