// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSCOMMI
{
    public string comp_no { get; set; }

    public string comm_no { get; set; }

    public string code_no { get; set; }

    public string code_txt { get; set; }

    public string para_code { get; set; }

    public string para_chr1 { get; set; }

    public string para_chr2 { get; set; }

    public string para_chr3 { get; set; }

    public decimal? para_num1 { get; set; }

    public decimal? para_num2 { get; set; }

    public decimal? para_num3 { get; set; }

    public DateTime? para_date1 { get; set; }

    public DateTime? para_date2 { get; set; }

    public DateTime? para_date3 { get; set; }

    public string use_yn { get; set; }

    public string memo { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime? crt_date { get; set; }
}