// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSCOM01
{
    public string comp_no { get; set; }

    /// <summary>
    /// 類別代碼
    /// </summary>
    public string COMM_NO { get; set; }

    /// <summary>
    /// 類別名稱
    /// </summary>
    public string COMM_NA { get; set; }

    /// <summary>
    /// 系統別 
    /// </summary>
    public string SYS_ID { get; set; }

    /// <summary>
    /// Code長度
    /// </summary>
    public decimal? CODE_LEN { get; set; }

    /// <summary>
    /// Text長度
    /// </summary>
    public decimal? TEXT_LEN { get; set; }

    /// <summary>
    /// 所屬群組
    /// </summary>
    public string BLG_GRP { get; set; }

    /// <summary>
    /// 修改碼
    /// </summary>
    public string MDY_CODE { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string MEMO { get; set; }

    /// <summary>
    /// 異動者代碼
    /// </summary>
    public string UPD_NO { get; set; }

    /// <summary>
    /// 異動日期
    /// </summary>
    public DateTime? UPD_DATE { get; set; }

    /// <summary>
    /// 建檔者代碼
    /// </summary>
    public string CRT_NO { get; set; }

    /// <summary>
    /// 建檔日期
    /// </summary>
    public DateTime? CRT_DATE { get; set; }

    /// <summary>
    /// 程式名稱
    /// </summary>
    public string PROG_NO { get; set; }

    /// <summary>
    /// 使用區分
    /// </summary>
    public string PROG_ID { get; set; }

    /// <summary>
    /// Table名稱
    /// </summary>
    public string TABLE_NA { get; set; }

    /// <summary>
    /// Table名稱
    /// </summary>
    public string FIELD_NA { get; set; }
}