// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSDESCIMG
{
    public string comp_no { get; set; }

    public int Id { get; set; }

    public string Title { get; set; }

    public string Path { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime? crt_date { get; set; }
}