// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSDTPMI
{
    public string comp_no { get; set; }

    public string pass_no { get; set; }

    public int mnuId { get; set; }

    public string PROG_NO { get; set; }

    public string can_use { get; set; }

    public string upd { get; set; }

    public string ins { get; set; }

    public string del { get; set; }

    public string qur { get; set; }

    public string prt { get; set; }

    public string saveas { get; set; }

    public string display { get; set; }

    public string other { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }

    public string crt_no { get; set; }

    public DateTime? crt_date { get; set; }
}