// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSLOGTABLE
{
    public string LOG_TABLE_NAME { get; set; }

    public string TABLE_NAME { get; set; }

    public DateTime CREATE_DATE { get; set; }

    public bool IS_MAIN_LOG_TABLE { get; set; }

    public bool IS_ARCHIVE { get; set; }

    public string ARCHIVE_NO { get; set; }

    public DateTime? ARCHIVE_DATE { get; set; }

    public string RESTORE_NO { get; set; }

    public DateTime? RESTORE_DATE { get; set; }
}