// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSLOG
{
    /// <summary>
    /// 流水號
    /// </summary>
    public decimal id { get; set; }

    /// <summary>
    /// 日期
    /// </summary>
    public DateTime date { get; set; }

    /// <summary>
    /// 線程
    /// </summary>
    public string thread { get; set; }

    /// <summary>
    /// 程式名稱
    /// </summary>
    public string program { get; set; }

    /// <summary>
    /// 級別
    /// </summary>
    public string level { get; set; }

    /// <summary>
    /// 紀錄器
    /// </summary>
    public string logger { get; set; }

    /// <summary>
    /// 訊息
    /// </summary>
    public string message { get; set; }

    /// <summary>
    /// 錯誤訊息
    /// </summary>
    public string exception { get; set; }

    /// <summary>
    /// 使用者
    /// </summary>
    public string userid { get; set; }

    /// <summary>
    /// IP位置
    /// </summary>
    public string ipaddress { get; set; }
}