// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSMNUMI
{
    public string comp_no { get; set; }

    public string MNU_NO { get; set; }

    public int id { get; set; }

    public int parentId { get; set; }

    /// <summary>
    /// 同層選單順序(e.g. 11)
    /// </summary>
    public decimal sortNo { get; set; }

    /// <summary>
    /// 系統代號(e.g. SYS)
    /// </summary>
    public string sys_id { get; set; }

    /// <summary>
    /// 資料夾/程式代碼 (e.g. CTL0101M)
    /// </summary>
    public string prog_no { get; set; }

    /// <summary>
    /// 程式區別碼 (e.g. 0)
    /// </summary>
    public string prog_id { get; set; }

    /// <summary>
    /// 中文名稱 (e.g. 90-1-建檔)
    /// </summary>
    public string prog_na { get; set; }

    /// <summary>
    /// 選單類型 (e.g. M) M:資料夾 ,P:程式
    /// </summary>
    public string mnu_type { get; set; }

    public string sd { get; set; }

    public DateTime? sd_date { get; set; }

    public string pg { get; set; }

    public DateTime? pg_date { get; set; }

    public string pg_ok { get; set; }

    public string upl_ok { get; set; }

    public string str_type { get; set; }

    public string memo { get; set; }

    /// <summary>
    /// 是否完成 (e.g. Y) Y:完成,N:未完成
    /// </summary>
    public string clt_ok { get; set; }

    /// <summary>
    /// 最大查詢筆數 (e.g. 0) 0:不限制
    /// </summary>
    public decimal? maxqucnt { get; set; }

    public string user_item { get; set; }

    /// <summary>
    /// 說明
    /// </summary>
    public string helpme { get; set; }

    /// <summary>
    /// 程式Area路徑 (e.g. SYS)
    /// </summary>
    public string url_path { get; set; }

    /// <summary>
    /// 每月可執行日(e.g. 1;23;31) 1~31
    /// </summary>
    public string run_day { get; set; }

    /// <summary>
    /// 每星期可執行日(e.g. 1;5;7) 1~7
    /// </summary>
    public string run_wday { get; set; }

    /// <summary>
    /// 每天可執行時間起(e.g. 0800)
    /// </summary>
    public string run_time_e { get; set; }

    /// <summary>
    /// 每天可執行時間訖(e.g. 1400)
    /// </summary>
    public string run_time_b { get; set; }

    /// <summary>
    /// 異動人員
    /// </summary>
    public string upd_no { get; set; }

    /// <summary>
    /// 億
    /// </summary>
    public DateTime? upd_date { get; set; }

    /// <summary>
    /// 建立人員
    /// </summary>
    public string crt_no { get; set; }

    /// <summary>
    /// 建立時間
    /// </summary>
    public DateTime? crt_date { get; set; }
}