// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSMNULNG
{
    public string comp_no { get; set; }

    public string MNU_NO { get; set; }

    public int mnuId { get; set; }

    public int Id { get; set; }

    public string name { get; set; }
}