// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSNEWSTI
{
    public string comp_no { get; set; }

    public decimal news_no { get; set; }

    public string pass_no { get; set; }

    public string isread { get; set; }

    public string upd_no { get; set; }

    public string upd_date { get; set; }

    public string crt_no { get; set; }

    public string crt_date { get; set; }
}