// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSNEWSMI
{
    public string comp_no { get; set; }

    public decimal news_no { get; set; }

    public string news_date { get; set; }

    public DateTime? news_bdate { get; set; }

    public DateTime? news_edate { get; set; }

    public string news_title { get; set; }

    public string news_content { get; set; }

    public string news_isover { get; set; }

    public byte news_weight { get; set; }

    public string mod_user { get; set; }

    public string mod_dte { get; set; }

    public string crt_user { get; set; }

    public string crt_dte { get; set; }
}