// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSORGMI
{
    public string COMP_NO { get; set; }

    public string ORG_NO { get; set; }

    public string ORG_NA { get; set; }

    public string ORG_TYPE { get; set; }

    public string UP_ORG_NO { get; set; }

    public string UP3_ORG_NO { get; set; }

    public string UP4_ORG_NO { get; set; }

    public string UP5_ORG_NO { get; set; }

    public string UP6_ORG_NO { get; set; }

    public string UP7_ORG_NO { get; set; }

    public string UP8_ORG_NO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }
}