// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSPASHISTORY
{
    public string comp_no { get; set; }

    public string pass_no { get; set; }

    public string pwd_org { get; set; }

    public string pwd_salt_org { get; set; }

    public string pwd_history1 { get; set; }

    public string pwd_salt_history1 { get; set; }

    public string pwd_history2 { get; set; }

    public string pwd_salt_history2 { get; set; }

    public string pwd_history3 { get; set; }

    public string pwd_salt_history3 { get; set; }

    public string upd_no { get; set; }

    public DateTime? upd_date { get; set; }
}