// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSPASMI
{
    public string comp_no { get; set; }

    /// <summary>
    /// 使用者代碼(員工代碼)
    /// </summary>
    public string pass_no { get; set; }

    /// <summary>
    /// 使用者姓名
    /// </summary>
    public string pass_na { get; set; }

    /// <summary>
    /// 英文名稱
    /// </summary>
    public string pass_eng { get; set; }

    /// <summary>
    /// 使用者密碼
    /// </summary>
    public string pass_wd { get; set; }

    /// <summary>
    /// 密碼加鹽
    /// </summary>
    public string pass_salt { get; set; }

    /// <summary>
    /// 使用者區分 0-個人, 1-群組
    /// </summary>
    public string pass_code { get; set; }

    /// <summary>
    /// 統一編號(身份證)
    /// </summary>
    public string pass_id { get; set; }

    /// <summary>
    /// 部門代碼
    /// </summary>
    public string dpd_no { get; set; }

    /// <summary>
    /// 店別群組代碼
    /// </summary>
    public string ros_no { get; set; }

    /// <summary>
    /// 採購群組代碼
    /// </summary>
    public string rob_no { get; set; }

    /// <summary>
    /// 員工代碼
    /// </summary>
    public string emp_no { get; set; }

    /// <summary>
    /// 使用者等級 1:一般使用者, 2:業務承辦人員, 
    /// </summary>
    public string pass_type { get; set; }

    /// <summary>
    /// 特殊控制碼
    /// </summary>
    public string spe_code { get; set; }

    /// <summary>
    /// E_MAIL
    /// </summary>
    public string e_mail { get; set; }

    /// <summary>
    /// 店別代碼
    /// </summary>
    public string str_no { get; set; }

    /// <summary>
    /// 生效日期
    /// </summary>
    public DateTime? start_date { get; set; }

    /// <summary>
    /// 停用日期
    /// </summary>
    public DateTime? end_date { get; set; }

    /// <summary>
    /// 建檔者代碼
    /// </summary>
    public string crt_no { get; set; }

    /// <summary>
    /// 建檔日期
    /// </summary>
    public DateTime? crt_date { get; set; }

    /// <summary>
    /// 密碼重置日
    /// </summary>
    public DateTime? pwd_reset_date { get; set; }

    /// <summary>
    /// 密碼修改日
    /// </summary>
    public DateTime? pwd_chg_date { get; set; }

    /// <summary>
    /// 角色 sysrolmi
    /// </summary>
    public string rol_no { get; set; }

    /// <summary>
    /// 手機號碼
    /// </summary>
    public string tel_m { get; set; }

    /// <summary>
    /// 登入錯誤次數
    /// </summary>
    public string f_cnt { get; set; }

    /// <summary>
    /// 帳號狀態0.使用中1.停用2.刪除
    /// </summary>
    public string del_cd { get; set; }

    /// <summary>
    /// 最近登入日期
    /// </summary>
    public DateTime? ldate { get; set; }

    /// <summary>
    /// 最近無法登入日期
    /// </summary>
    public DateTime? fdate { get; set; }

    /// <summary>
    /// 異動者代碼
    /// </summary>
    public string upd_no { get; set; }

    /// <summary>
    /// 異動日期
    /// </summary>
    public DateTime? upd_date { get; set; }

    public string wd { get; set; }

    public string first_wd { get; set; }

    public DateTime? CLE_DATE_B { get; set; }

    public DateTime? CLE_DATE_E { get; set; }

    public string CLE_LEVEL { get; set; }
}