// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSPTGMI
{
    public string comp_no { get; set; }

    /// <summary>
    /// 使用者代碼
    /// </summary>
    public string PASS_NO { get; set; }

    /// <summary>
    /// 群組代碼
    /// </summary>
    public string GPASS_NO { get; set; }
}