// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSPASFG
{
    public string comp_no { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string pass_no { get; set; }

    /// <summary>
    /// 信箱
    /// </summary>
    public string e_mail { get; set; }

    /// <summary>
    /// 申請時間
    /// </summary>
    public DateTime apply_time { get; set; }

    /// <summary>
    /// 識別碼
    /// </summary>
    public string token { get; set; }
}