// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace INVwebAPI.Data.Entities;

public partial class SYSSTRMI
{
    public string COMP_NO { get; set; }

    public string STR_NO { get; set; }

    public string STR_NA { get; set; }

    public string STR_SN { get; set; }

    public string UP_ORG_NO { get; set; }

    public string LEADER { get; set; }

    public string BL_NO { get; set; }

    public string STR_LEVEL { get; set; }

    public string STR_TYPE { get; set; }

    public string STR_AREA { get; set; }

    public string TEL_ZNO { get; set; }

    public string TEL_NO { get; set; }

    public string FAX_ZNO { get; set; }

    public string FAX_NO { get; set; }

    public string STR_ZCODE { get; set; }

    public string STR_ADDR { get; set; }

    public string E_MAIL { get; set; }

    public decimal? STR_SIZE { get; set; }

    public decimal? UP_FLOOR { get; set; }

    public decimal? DN_FLOOR { get; set; }

    public decimal? CAR_QTY { get; set; }

    public decimal? BIC_QTY { get; set; }

    public decimal? EMP_QTY { get; set; }

    public decimal? ECR_QTY { get; set; }

    public DateTime? OPEN_DATE { get; set; }

    public DateTime? CLOSE_DATE { get; set; }

    public string TAX_NO { get; set; }

    public string BNK_NO { get; set; }

    public string BNK_ACNO { get; set; }

    public string UPD_NO { get; set; }

    public DateTime? UPD_DATE { get; set; }

    public string CRT_NO { get; set; }

    public DateTime? CRT_DATE { get; set; }

    public string SYS_NO { get; set; }

    public DateTime? SYS_DATE { get; set; }

    public DateTime? EINV_DATEB { get; set; }

    public string BL_NAME { get; set; }

    public string VIP_TYPE { get; set; }

    public string TOKEN_KEY { get; set; }

    public string INVCHECK_YN { get; set; }

    public string SERVICE_HOURSB { get; set; }

    public string SERVICE_HOURSE { get; set; }

    public string IS_OPEN_NOW { get; set; }

    public string DEALER { get; set; }

    public string FRCOMPBLNO { get; set; }
}